### ISSUE TITLE
Error on startup (Mac OS Sierra)

### ISSUE THREAD

**Issue by subwaymatch** [subwaymatch/hackbrowser#26]
```
Yes-MacBook-Pro:hackbrowser root# ./node_modules/.bin/electron .
App threw an error during load
Error: ENOENT: no such file or directory, mkdir '/var/root/Library/Application Support/hackbrowser/logs'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Object.<anonymous> (/Users/yejoopark/Downloads/hackbrowser/main.js:18:5)
    at Object.<anonymous> (/Users/yejoopark/Downloads/hackbrowser/main.js:36:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/Users/yejoopark/Downloads/hackbrowser/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/Users/yejoopark/Downloads/hackbrowser/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:325:5)
2017-04-23 12:52:21.797 Electron[1749:134489] Spell server connection invalidated
```

**Comment by subwaymatch** [comment]
Git cloned the directory into /Users/yejoopark/Download/hackbrowser signed in as `root`. 

Seems to be a permission issue.
